@apiurl = http://localhost:3000
@eventId = 77dc1436-a653-49a1-bd57-18db7b801b9b

###
GET {{apiurl}}/events


###
POST {{apiurl}}/events
Content-Type: application/json

{
  "name": "New Event 3",
  "date": "2025-10-10T00:00:00.000z",
  "description": "this is a new event created throught .http archieve",
  "price": 32.99
}


###
GET {{apiurl}}/events/{{eventId}}


### Spots ###
@spotId = 2a707a16-bf1c-4845-87c4-fc632bf96d98

GET {{apiurl}}/events/{{eventId}}/spots

###
POST {{apiurl}}/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A1"
}

### 
GET {{apiurl}}/events/{{eventId}}/spots/{{spotId}}